#!/system/bin/sh

model=`getprop ro.product.model`
mount -o remount,rw /system
rm /system/usr/keylayout/gpio-keys.kl
if [ "$model" = "LG-D290" ] || [ "$model" = "LG-D290n" ]; then
	ln -s /system/usr/keylayout/gpio-keys_d290.kl /system/usr/keylayout/gpio-keys.kl 
else
	ln -s /system/usr/keylayout/gpio-keys_d295.kl /system/usr/keylayout/gpio-keys.kl
fi


mount -o remount,ro /system
